//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LojaAppWPF.WS {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CompositeType", Namespace="http://schemas.datacontract.org/2004/07/LojaWcf")]
    [System.SerializableAttribute()]
    public partial class CompositeType : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool BoolValueField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StringValueField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool BoolValue {
            get {
                return this.BoolValueField;
            }
            set {
                if ((this.BoolValueField.Equals(value) != true)) {
                    this.BoolValueField = value;
                    this.RaisePropertyChanged("BoolValue");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string StringValue {
            get {
                return this.StringValueField;
            }
            set {
                if ((object.ReferenceEquals(this.StringValueField, value) != true)) {
                    this.StringValueField = value;
                    this.RaisePropertyChanged("StringValue");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Fabricante", Namespace="http://schemas.datacontract.org/2004/07/LojaWcf")]
    [System.SerializableAttribute()]
    public partial class Fabricante : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescricaoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Descricao {
            get {
                return this.DescricaoField;
            }
            set {
                if ((object.ReferenceEquals(this.DescricaoField, value) != true)) {
                    this.DescricaoField = value;
                    this.RaisePropertyChanged("Descricao");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Veiculo", Namespace="http://schemas.datacontract.org/2004/07/LojaWcf")]
    [System.SerializableAttribute()]
    public partial class Veiculo : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> AnoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> DataCompraField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> DataVendaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> IdFabricanteField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ModeloField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<decimal> PrecoVendaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<decimal> ValorCompraField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<decimal> ValorVendaField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> Ano {
            get {
                return this.AnoField;
            }
            set {
                if ((this.AnoField.Equals(value) != true)) {
                    this.AnoField = value;
                    this.RaisePropertyChanged("Ano");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> DataCompra {
            get {
                return this.DataCompraField;
            }
            set {
                if ((this.DataCompraField.Equals(value) != true)) {
                    this.DataCompraField = value;
                    this.RaisePropertyChanged("DataCompra");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> DataVenda {
            get {
                return this.DataVendaField;
            }
            set {
                if ((this.DataVendaField.Equals(value) != true)) {
                    this.DataVendaField = value;
                    this.RaisePropertyChanged("DataVenda");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> IdFabricante {
            get {
                return this.IdFabricanteField;
            }
            set {
                if ((this.IdFabricanteField.Equals(value) != true)) {
                    this.IdFabricanteField = value;
                    this.RaisePropertyChanged("IdFabricante");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Modelo {
            get {
                return this.ModeloField;
            }
            set {
                if ((object.ReferenceEquals(this.ModeloField, value) != true)) {
                    this.ModeloField = value;
                    this.RaisePropertyChanged("Modelo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> PrecoVenda {
            get {
                return this.PrecoVendaField;
            }
            set {
                if ((this.PrecoVendaField.Equals(value) != true)) {
                    this.PrecoVendaField = value;
                    this.RaisePropertyChanged("PrecoVenda");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> ValorCompra {
            get {
                return this.ValorCompraField;
            }
            set {
                if ((this.ValorCompraField.Equals(value) != true)) {
                    this.ValorCompraField = value;
                    this.RaisePropertyChanged("ValorCompra");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> ValorVenda {
            get {
                return this.ValorVendaField;
            }
            set {
                if ((this.ValorVendaField.Equals(value) != true)) {
                    this.ValorVendaField = value;
                    this.RaisePropertyChanged("ValorVenda");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="WS.IService1")]
    public interface IService1 {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetData", ReplyAction="http://tempuri.org/IService1/GetDataResponse")]
        string GetData(int value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetData", ReplyAction="http://tempuri.org/IService1/GetDataResponse")]
        System.Threading.Tasks.Task<string> GetDataAsync(int value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetDataUsingDataContract", ReplyAction="http://tempuri.org/IService1/GetDataUsingDataContractResponse")]
        LojaAppWPF.WS.CompositeType GetDataUsingDataContract(LojaAppWPF.WS.CompositeType composite);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetDataUsingDataContract", ReplyAction="http://tempuri.org/IService1/GetDataUsingDataContractResponse")]
        System.Threading.Tasks.Task<LojaAppWPF.WS.CompositeType> GetDataUsingDataContractAsync(LojaAppWPF.WS.CompositeType composite);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/FabricanteSelect", ReplyAction="http://tempuri.org/IService1/FabricanteSelectResponse")]
        LojaAppWPF.WS.Fabricante[] FabricanteSelect();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/FabricanteSelect", ReplyAction="http://tempuri.org/IService1/FabricanteSelectResponse")]
        System.Threading.Tasks.Task<LojaAppWPF.WS.Fabricante[]> FabricanteSelectAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/FabricanteInsert", ReplyAction="http://tempuri.org/IService1/FabricanteInsertResponse")]
        void FabricanteInsert(int id, string descricao);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/FabricanteInsert", ReplyAction="http://tempuri.org/IService1/FabricanteInsertResponse")]
        System.Threading.Tasks.Task FabricanteInsertAsync(int id, string descricao);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/FabricanteUpdate", ReplyAction="http://tempuri.org/IService1/FabricanteUpdateResponse")]
        void FabricanteUpdate(int id, string descricao);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/FabricanteUpdate", ReplyAction="http://tempuri.org/IService1/FabricanteUpdateResponse")]
        System.Threading.Tasks.Task FabricanteUpdateAsync(int id, string descricao);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/FabricanteDelete", ReplyAction="http://tempuri.org/IService1/FabricanteDeleteResponse")]
        void FabricanteDelete(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/FabricanteDelete", ReplyAction="http://tempuri.org/IService1/FabricanteDeleteResponse")]
        System.Threading.Tasks.Task FabricanteDeleteAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/VeiculoSelectDisponiveis", ReplyAction="http://tempuri.org/IService1/VeiculoSelectDisponiveisResponse")]
        LojaAppWPF.WS.Veiculo[] VeiculoSelectDisponiveis();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/VeiculoSelectDisponiveis", ReplyAction="http://tempuri.org/IService1/VeiculoSelectDisponiveisResponse")]
        System.Threading.Tasks.Task<LojaAppWPF.WS.Veiculo[]> VeiculoSelectDisponiveisAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/VeiculoSelectVendidos", ReplyAction="http://tempuri.org/IService1/VeiculoSelectVendidosResponse")]
        LojaAppWPF.WS.Veiculo[] VeiculoSelectVendidos();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/VeiculoSelectVendidos", ReplyAction="http://tempuri.org/IService1/VeiculoSelectVendidosResponse")]
        System.Threading.Tasks.Task<LojaAppWPF.WS.Veiculo[]> VeiculoSelectVendidosAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/VeiculoSelect", ReplyAction="http://tempuri.org/IService1/VeiculoSelectResponse")]
        LojaAppWPF.WS.Veiculo[] VeiculoSelect();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/VeiculoSelect", ReplyAction="http://tempuri.org/IService1/VeiculoSelectResponse")]
        System.Threading.Tasks.Task<LojaAppWPF.WS.Veiculo[]> VeiculoSelectAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/VeiculoInsert", ReplyAction="http://tempuri.org/IService1/VeiculoInsertResponse")]
        void VeiculoInsert(int id, string modelo, int ano, int idFab, System.DateTime dataCompra, decimal valorCompra);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/VeiculoInsert", ReplyAction="http://tempuri.org/IService1/VeiculoInsertResponse")]
        System.Threading.Tasks.Task VeiculoInsertAsync(int id, string modelo, int ano, int idFab, System.DateTime dataCompra, decimal valorCompra);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/VeiculoUpdate", ReplyAction="http://tempuri.org/IService1/VeiculoUpdateResponse")]
        void VeiculoUpdate(int id, decimal precoVenda, System.DateTime dataVenda, decimal valorVenda);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/VeiculoUpdate", ReplyAction="http://tempuri.org/IService1/VeiculoUpdateResponse")]
        System.Threading.Tasks.Task VeiculoUpdateAsync(int id, decimal precoVenda, System.DateTime dataVenda, decimal valorVenda);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/VeiculoDelete", ReplyAction="http://tempuri.org/IService1/VeiculoDeleteResponse")]
        void VeiculoDelete(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/VeiculoDelete", ReplyAction="http://tempuri.org/IService1/VeiculoDeleteResponse")]
        System.Threading.Tasks.Task VeiculoDeleteAsync(int id);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IService1Channel : LojaAppWPF.WS.IService1, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Service1Client : System.ServiceModel.ClientBase<LojaAppWPF.WS.IService1>, LojaAppWPF.WS.IService1 {
        
        public Service1Client() {
        }
        
        public Service1Client(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Service1Client(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string GetData(int value) {
            return base.Channel.GetData(value);
        }
        
        public System.Threading.Tasks.Task<string> GetDataAsync(int value) {
            return base.Channel.GetDataAsync(value);
        }
        
        public LojaAppWPF.WS.CompositeType GetDataUsingDataContract(LojaAppWPF.WS.CompositeType composite) {
            return base.Channel.GetDataUsingDataContract(composite);
        }
        
        public System.Threading.Tasks.Task<LojaAppWPF.WS.CompositeType> GetDataUsingDataContractAsync(LojaAppWPF.WS.CompositeType composite) {
            return base.Channel.GetDataUsingDataContractAsync(composite);
        }
        
        public LojaAppWPF.WS.Fabricante[] FabricanteSelect() {
            return base.Channel.FabricanteSelect();
        }
        
        public System.Threading.Tasks.Task<LojaAppWPF.WS.Fabricante[]> FabricanteSelectAsync() {
            return base.Channel.FabricanteSelectAsync();
        }
        
        public void FabricanteInsert(int id, string descricao) {
            base.Channel.FabricanteInsert(id, descricao);
        }
        
        public System.Threading.Tasks.Task FabricanteInsertAsync(int id, string descricao) {
            return base.Channel.FabricanteInsertAsync(id, descricao);
        }
        
        public void FabricanteUpdate(int id, string descricao) {
            base.Channel.FabricanteUpdate(id, descricao);
        }
        
        public System.Threading.Tasks.Task FabricanteUpdateAsync(int id, string descricao) {
            return base.Channel.FabricanteUpdateAsync(id, descricao);
        }
        
        public void FabricanteDelete(int id) {
            base.Channel.FabricanteDelete(id);
        }
        
        public System.Threading.Tasks.Task FabricanteDeleteAsync(int id) {
            return base.Channel.FabricanteDeleteAsync(id);
        }
        
        public LojaAppWPF.WS.Veiculo[] VeiculoSelectDisponiveis() {
            return base.Channel.VeiculoSelectDisponiveis();
        }
        
        public System.Threading.Tasks.Task<LojaAppWPF.WS.Veiculo[]> VeiculoSelectDisponiveisAsync() {
            return base.Channel.VeiculoSelectDisponiveisAsync();
        }
        
        public LojaAppWPF.WS.Veiculo[] VeiculoSelectVendidos() {
            return base.Channel.VeiculoSelectVendidos();
        }
        
        public System.Threading.Tasks.Task<LojaAppWPF.WS.Veiculo[]> VeiculoSelectVendidosAsync() {
            return base.Channel.VeiculoSelectVendidosAsync();
        }
        
        public LojaAppWPF.WS.Veiculo[] VeiculoSelect() {
            return base.Channel.VeiculoSelect();
        }
        
        public System.Threading.Tasks.Task<LojaAppWPF.WS.Veiculo[]> VeiculoSelectAsync() {
            return base.Channel.VeiculoSelectAsync();
        }
        
        public void VeiculoInsert(int id, string modelo, int ano, int idFab, System.DateTime dataCompra, decimal valorCompra) {
            base.Channel.VeiculoInsert(id, modelo, ano, idFab, dataCompra, valorCompra);
        }
        
        public System.Threading.Tasks.Task VeiculoInsertAsync(int id, string modelo, int ano, int idFab, System.DateTime dataCompra, decimal valorCompra) {
            return base.Channel.VeiculoInsertAsync(id, modelo, ano, idFab, dataCompra, valorCompra);
        }
        
        public void VeiculoUpdate(int id, decimal precoVenda, System.DateTime dataVenda, decimal valorVenda) {
            base.Channel.VeiculoUpdate(id, precoVenda, dataVenda, valorVenda);
        }
        
        public System.Threading.Tasks.Task VeiculoUpdateAsync(int id, decimal precoVenda, System.DateTime dataVenda, decimal valorVenda) {
            return base.Channel.VeiculoUpdateAsync(id, precoVenda, dataVenda, valorVenda);
        }
        
        public void VeiculoDelete(int id) {
            base.Channel.VeiculoDelete(id);
        }
        
        public System.Threading.Tasks.Task VeiculoDeleteAsync(int id) {
            return base.Channel.VeiculoDeleteAsync(id);
        }
    }
}
